export type Region = "no" | "se" | "dk" | "fi";

export interface GuideLocale {
  title: string;
  description: string;
  h1: string;
  intro: string;
  cta_heading: string;
  cta_body: string;
  faq_question: string;
  faq_answer: string;
  empty: string;
  breadcrumb_home: string;
  breadcrumb_guides: string;
  faq_heading: string;
  bottom_heading: string;
  bottom_body: string;
}

export interface GuideConfig {
  slug: string;
  mood_tags: string[];
  locales: Record<Region, GuideLocale>;
}

export const REGIONS: Region[] = ["no", "se", "dk", "fi"];

export const REGION_HREFLANG: Record<Region, string> = {
  no: "nb-NO",
  se: "sv-SE",
  dk: "da-DK",
  fi: "fi-FI",
};

const BREADCRUMBS: Record<Region, { home: string; guides: string }> = {
  no: { home: "Hjem", guides: "Guider" },
  se: { home: "Hem", guides: "Guider" },
  dk: { home: "Hjem", guides: "Guider" },
  fi: { home: "Etusivu", guides: "Oppaat" },
};

function bc(r: Region) {
  return BREADCRUMBS[r];
}

export const MOOD_GUIDES: GuideConfig[] = [
  {
    slug: "perfekt-fredagskveld",
    mood_tags: ["Perfekt for fredagskveld"],
    locales: {
      no: {
        title: "Perfekt for fredagskveld – Filmer og serier | Logflix",
        description: "De beste filmene og seriene for fredagskvelden. Finn din neste favoritt på Logflix.",
        h1: "Perfekt for fredagskveld",
        intro: "Ukens beste øyeblikk fortjener den rette filmen. Her er titler som passer perfekt til fredagskvelden — enten du vil le, gråte eller bare koble av.",
        cta_heading: "Ikke enige om fredagsfilmen?",
        cta_body: "La Se Sammen avgjøre — sveip hver for dere og finn filmen dere begge vil se.",
        faq_question: "Hvilke filmer passer best til fredagskveld?",
        faq_answer: "Logflix kuraterer filmer og serier med mood-taggen «Perfekt for fredagskveld» — titler som er lette å komme inn i og gir god stemning.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        ...bc("no"), breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for fredagskvelden?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Perfekt för fredagskvällen – Filmer och serier | Logflix",
        description: "De bästa filmerna och serierna för fredagskvällen. Hitta din nästa favorit på Logflix.",
        h1: "Perfekt för fredagskvällen",
        intro: "Veckans bästa ögonblick förtjänar rätt film. Här är titlar som passar perfekt till fredagskvällen — oavsett om du vill skratta, gråta eller bara koppla av.",
        cta_heading: "Inte överens om fredagsfilmen?",
        cta_body: "Låt Se Sammen avgöra — swipea var för sig och hitta filmen ni båda vill se.",
        faq_question: "Vilka filmer passar bäst till fredagskväll?",
        faq_answer: "Logflix kuraterar filmer och serier med mood-taggen «Perfekt för fredagskvällen» — titlar som är lätta att komma in i och ger bra stämning.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för fredagskvällen?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Perfekt til fredagsaften – Film og serier | Logflix",
        description: "De bedste film og serier til fredagsaften. Find din næste favorit på Logflix.",
        h1: "Perfekt til fredagsaften",
        intro: "Ugens bedste øjeblik fortjener den rigtige film. Her er titler der passer perfekt til fredagsaften — uanset om du vil grine, græde eller bare slappe af.",
        cta_heading: "Kan I ikke blive enige om fredagsfilmen?",
        cta_body: "Lad Se Sammen afgøre — swipe hver for jer og find filmen I begge vil se.",
        faq_question: "Hvilke film passer bedst til fredagsaften?",
        faq_answer: "Logflix kuraterer film og serier med mood-taggen «Perfekt til fredagsaften» — titler der er lette at komme ind i og giver god stemning.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til fredagsaften?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Täydellinen perjantai-iltaan – Elokuvat ja sarjat | Logflix",
        description: "Parhaat elokuvat ja sarjat perjantai-iltaan. Löydä seuraava suosikkisi Logflixistä.",
        h1: "Täydellinen perjantai-iltaan",
        intro: "Viikon paras hetki ansaitsee oikean elokuvan. Tässä on nimikkeitä jotka sopivat täydellisesti perjantai-iltaan — halusitpa nauraa, itkeä tai vain rentoutua.",
        cta_heading: "Etkö pääse sopimukseen perjantain elokuvasta?",
        cta_body: "Anna Se Sammen päättää — selaa erikseen ja löydä elokuva josta molemmat pitävät.",
        faq_question: "Mitkä elokuvat sopivat parhaiten perjantai-iltaan?",
        faq_answer: "Logflix kuratoi elokuvia ja sarjoja mood-tagilla «Perfekt for fredagskveld» — nimikkeitä joihin on helppo päästä sisään ja jotka luovat hyvää tunnelmaa.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis perjantai-iltaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "se-alene-i-morket",
    mood_tags: ["Se alene i mørket"],
    locales: {
      no: {
        title: "Se alene i mørket – Skumle filmer og serier | Logflix",
        description: "De beste filmene og seriene å se alene i mørket. Tør du?",
        h1: "Se alene i mørket",
        intro: "Noen filmer er laget for å sees alene, med lyset av. Her er titler som gir deg gåsehud — perfekt for de modige kveldene.",
        cta_heading: "Tør du se alene?",
        cta_body: "Eller finn en å se med — bruk Se Sammen og match på den skumleste filmen.",
        faq_question: "Hvilke filmer er best å se alene i mørket?",
        faq_answer: "Logflix har kuratert en liste med filmer og serier tagget «Se alene i mørket» — titler med intens stemning som fungerer best på egenhånd.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for en skummel kveld?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Se ensam i mörkret – Läskiga filmer och serier | Logflix",
        description: "De bästa filmerna och serierna att se ensam i mörkret. Vågar du?",
        h1: "Se ensam i mörkret",
        intro: "Vissa filmer är gjorda för att ses ensam, med lampan släckt. Här är titlar som ger dig gåshud — perfekt för de modiga kvällarna.",
        cta_heading: "Vågar du se ensam?",
        cta_body: "Eller hitta någon att se med — använd Se Sammen och matcha på den läskigaste filmen.",
        faq_question: "Vilka filmer är bäst att se ensam i mörkret?",
        faq_answer: "Logflix har kuraterat en lista med filmer och serier taggade «Se alene i mørket» — titlar med intensiv stämning som fungerar bäst på egen hand.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för en läskig kväll?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Se alene i mørket – Uhyggelige film og serier | Logflix",
        description: "De bedste film og serier at se alene i mørket. Tør du?",
        h1: "Se alene i mørket",
        intro: "Nogle film er lavet til at ses alene, med lyset slukket. Her er titler der giver dig gåsehud — perfekt til de modige aftener.",
        cta_heading: "Tør du se alene?",
        cta_body: "Eller find nogen at se med — brug Se Sammen og match på den uhyggeligste film.",
        faq_question: "Hvilke film er bedst at se alene i mørket?",
        faq_answer: "Logflix har kurateret en liste med film og serier tagget «Se alene i mørket» — titler med intens stemning der fungerer bedst på egen hånd.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til en uhyggelig aften?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Katso yksin pimeässä – Pelottavat elokuvat ja sarjat | Logflix",
        description: "Parhaat elokuvat ja sarjat katsottavaksi yksin pimeässä. Uskaltaisitko?",
        h1: "Katso yksin pimeässä",
        intro: "Jotkut elokuvat on tehty katsottavaksi yksin, valot sammutettuna. Tässä on nimikkeitä jotka antavat kylmiä väreitä — täydellistä rohkeille illoille.",
        cta_heading: "Uskaltaisitko katsoa yksin?",
        cta_body: "Tai löydä joku katsomaan kanssasi — käytä Se Sammen ja löydä pelottavin elokuva.",
        faq_question: "Mitkä elokuvat ovat parhaita katsottavaksi yksin pimeässä?",
        faq_answer: "Logflix on kuratoinut listan elokuvista ja sarjoista tagilla «Se alene i mørket» — nimikkeitä joissa on intensiivinen tunnelma.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis pelottavaan iltaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "filmkveld-for-to",
    mood_tags: ["Filmkveld for to"],
    locales: {
      no: {
        title: "Filmkveld for to – Romantiske filmer og serier | Logflix",
        description: "De beste filmene og seriene for en koselig filmkveld for to. Finn den perfekte datefilmen.",
        h1: "Filmkveld for to",
        intro: "Enten det er første date eller tusende kveld på sofaen — her er titler som setter stemningen for en perfekt filmkveld for to.",
        cta_heading: "Kan ikke bestemme dere?",
        cta_body: "La Se Sammen avgjøre — sveip hver for dere og finn filmen dere begge vil se.",
        faq_question: "Hvilke filmer passer best til filmkveld for to?",
        faq_answer: "Logflix kuraterer filmer og serier med mood-taggen «Filmkveld for to» — romantiske, varme og stemningsfulle titler for par.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for filmkveld?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Filmkväll för två – Romantiska filmer och serier | Logflix",
        description: "De bästa filmerna och serierna för en mysig filmkväll för två. Hitta den perfekta dejt-filmen.",
        h1: "Filmkväll för två",
        intro: "Oavsett om det är första dejten eller tusende kvällen i soffan — här är titlar som sätter stämningen för en perfekt filmkväll för två.",
        cta_heading: "Kan ni inte bestämma er?",
        cta_body: "Låt Se Sammen avgöra — swipea var för sig och hitta filmen ni båda vill se.",
        faq_question: "Vilka filmer passar bäst till filmkväll för två?",
        faq_answer: "Logflix kuraterar filmer och serier med mood-taggen «Filmkväll för två» — romantiska, varma och stämningsfulla titlar för par.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för filmkväll?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Filmaften for to – Romantiske film og serier | Logflix",
        description: "De bedste film og serier til en hyggelig filmaften for to. Find den perfekte date-film.",
        h1: "Filmaften for to",
        intro: "Uanset om det er første date eller tusinde aften i sofaen — her er titler der sætter stemningen for en perfekt filmaften for to.",
        cta_heading: "Kan I ikke bestemme jer?",
        cta_body: "Lad Se Sammen afgøre — swipe hver for jer og find filmen I begge vil se.",
        faq_question: "Hvilke film passer bedst til filmaften for to?",
        faq_answer: "Logflix kuraterer film og serier med mood-taggen «Filmaften for to» — romantiske, varme og stemningsfulde titler for par.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til filmaften?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Elokuvailta kahdelle – Romanttiset elokuvat ja sarjat | Logflix",
        description: "Parhaat elokuvat ja sarjat kahdelle. Löydä täydellinen treffielokuva.",
        h1: "Elokuvailta kahdelle",
        intro: "Olipa kyse ensimmäisestä treffeistä tai tuhannenesta illasta sohvalla — tässä on nimikkeitä jotka luovat tunnelman täydelliselle elokuvaillalle kahdelle.",
        cta_heading: "Etkö pääse sopimukseen?",
        cta_body: "Anna Se Sammen päättää — selaa erikseen ja löydä elokuva josta molemmat pitävät.",
        faq_question: "Mitkä elokuvat sopivat parhaiten kahdelle?",
        faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Filmkveld for to» — romanttisia, lämpimiä ja tunnelmallisia nimikkeitä pareille.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis elokuvailtaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "krever-full-oppmerksomhet",
    mood_tags: ["Krever full oppmerksomhet"],
    locales: {
      no: {
        title: "Krever full oppmerksomhet – Intense filmer og serier | Logflix",
        description: "Filmer og serier som krever at du legger bort telefonen. Intense, komplekse og engasjerende.",
        h1: "Krever full oppmerksomhet",
        intro: "Legg bort telefonen. Disse titlene krever at du er til stede — komplekse historier, overraskende vendinger og lag på lag med mening.",
        cta_heading: "Klar for noe intenst?",
        cta_body: "Finn noen å diskutere med etterpå — bruk Se Sammen og match på en film som gir dere noe å snakke om.",
        faq_question: "Hvilke filmer krever full oppmerksomhet?",
        faq_answer: "Logflix tagger filmer og serier som «Krever full oppmerksomhet» — titler med komplekse plot og intense opplevelser.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for å fokusere?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Kräver full uppmärksamhet – Intensiva filmer och serier | Logflix",
        description: "Filmer och serier som kräver att du lägger undan telefonen. Intensiva, komplexa och engagerande.",
        h1: "Kräver full uppmärksamhet",
        intro: "Lägg undan telefonen. De här titlarna kräver att du är närvarande — komplexa berättelser, överraskande vändningar och lager på lager av mening.",
        cta_heading: "Redo för något intensivt?",
        cta_body: "Hitta någon att diskutera med efteråt — använd Se Sammen och matcha på en film som ger er något att prata om.",
        faq_question: "Vilka filmer kräver full uppmärksamhet?",
        faq_answer: "Logflix taggar filmer och serier som «Kräver full uppmärksamhet» — titlar med komplexa handlingar och intensiva upplevelser.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo att fokusera?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Kræver fuld opmærksomhed – Intense film og serier | Logflix",
        description: "Film og serier der kræver at du lægger telefonen væk. Intense, komplekse og engagerende.",
        h1: "Kræver fuld opmærksomhed",
        intro: "Læg telefonen væk. Disse titler kræver at du er til stede — komplekse historier, overraskende vendinger og lag på lag af mening.",
        cta_heading: "Klar til noget intenst?",
        cta_body: "Find nogen at diskutere med bagefter — brug Se Sammen og match på en film der giver jer noget at snakke om.",
        faq_question: "Hvilke film kræver fuld opmærksomhed?",
        faq_answer: "Logflix tagger film og serier som «Kræver fuld opmærksomhed» — titler med komplekse plots og intense oplevelser.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til at fokusere?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Vaatii täyden huomion – Intensiiviset elokuvat ja sarjat | Logflix",
        description: "Elokuvat ja sarjat jotka vaativat täyden huomiosi. Intensiivisiä, monimutkaisia ja mukaansatempaavia.",
        h1: "Vaatii täyden huomion",
        intro: "Laita puhelin pois. Nämä nimikkeet vaativat läsnäoloa — monimutkaisia tarinoita, yllättäviä käänteitä ja kerros kerrokselta merkitystä.",
        cta_heading: "Valmis johonkin intensiiviseen?",
        cta_body: "Löydä joku keskustelemaan jälkeenpäin — käytä Se Sammen ja löydä elokuva josta on puhuttavaa.",
        faq_question: "Mitkä elokuvat vaativat täyden huomion?",
        faq_answer: "Logflix merkitsee elokuvia ja sarjoja tagilla «Krever full oppmerksomhet» — nimikkeitä joissa on monimutkaisia juonia ja intensiivisiä kokemuksia.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis keskittymään?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "lett-og-morsom",
    mood_tags: ["Lett og morsom"],
    locales: {
      no: {
        title: "Lett og morsom – Komedier og feelgood | Logflix",
        description: "Filmer og serier som er lette å se og garantert gir deg et smil. Perfekt for avslapping.",
        h1: "Lett og morsom",
        intro: "Noen ganger trenger du bare noe lett og morsomt. Her er titler som ikke krever mye av deg — bare at du er klar for å le.",
        cta_heading: "Trenger dere noe alle liker?",
        cta_body: "Bruk Se Sammen og finn den morsomste filmen dere begge vil se.",
        faq_question: "Hvilke filmer er lette og morsomme?",
        faq_answer: "Logflix kuraterer filmer og serier tagget «Lett og morsom» — titler for avslapping og godt humør.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for å le?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Lätt och rolig – Komedier och feelgood | Logflix",
        description: "Filmer och serier som är lätta att se och garanterat ger dig ett leende. Perfekt för avkoppling.",
        h1: "Lätt och rolig",
        intro: "Ibland behöver du bara något lätt och roligt. Här är titlar som inte kräver mycket av dig — bara att du är redo att skratta.",
        cta_heading: "Behöver ni något alla gillar?",
        cta_body: "Använd Se Sammen och hitta den roligaste filmen ni båda vill se.",
        faq_question: "Vilka filmer är lätta och roliga?",
        faq_answer: "Logflix kuraterar filmer och serier taggade «Lätt och rolig» — titlar för avkoppling och gott humör.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo att skratta?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Let og sjov – Komedier og feelgood | Logflix",
        description: "Film og serier der er lette at se og garanteret giver dig et smil. Perfekt til afslapning.",
        h1: "Let og sjov",
        intro: "Nogle gange har du bare brug for noget let og sjovt. Her er titler der ikke kræver meget af dig — bare at du er klar til at grine.",
        cta_heading: "Har I brug for noget alle kan lide?",
        cta_body: "Brug Se Sammen og find den sjoveste film I begge vil se.",
        faq_question: "Hvilke film er lette og sjove?",
        faq_answer: "Logflix kuraterer film og serier tagget «Let og sjov» — titler til afslapning og godt humør.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til at grine?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Kevyt ja hauska – Komediat ja feelgood | Logflix",
        description: "Helposti katsottavia elokuvia ja sarjoja jotka takaavat hymyn. Täydellistä rentoutumiseen.",
        h1: "Kevyt ja hauska",
        intro: "Joskus tarvitset vain jotain kevyttä ja hauskaa. Tässä on nimikkeitä jotka eivät vaadi sinulta paljon — vain valmiutta nauraa.",
        cta_heading: "Tarvitsetteko jotain josta kaikki pitävät?",
        cta_body: "Käytä Se Sammen ja löydä hauskin elokuva josta molemmat pitävät.",
        faq_question: "Mitkä elokuvat ovat kevyitä ja hauskoja?",
        faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Lett og morsom» — nimikkeitä rentoutumiseen ja hyvään mieleen.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis nauramaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "tung-og-tankevekkende",
    mood_tags: ["Tung og tankevekkende"],
    locales: {
      no: {
        title: "Tung og tankevekkende – Filmer som setter seg | Logflix",
        description: "Filmer og serier som setter seg i deg lenge etter rulleteksten. Dype, intense og uforglemmelige.",
        h1: "Tung og tankevekkende",
        intro: "Disse titlene er ikke for de som vil koble av. De er for de som vil føle noe ekte — historier som setter seg og gir deg noe å tenke på i dagevis.",
        cta_heading: "Vil du dele opplevelsen?",
        cta_body: "Finn noen å se med — bruk Se Sammen og match på en film som gir dere noe å snakke om.",
        faq_question: "Hvilke filmer er tunge og tankevekkende?",
        faq_answer: "Logflix kuraterer filmer og serier tagget «Tung og tankevekkende» — dype, intense titler som setter seg.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for noe dypt?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Tung och tankeväckande – Filmer som fastnar | Logflix",
        description: "Filmer och serier som fastnar i dig länge efter eftertexterna. Djupa, intensiva och oförglömliga.",
        h1: "Tung och tankeväckande",
        intro: "De här titlarna är inte för de som vill koppla av. De är för de som vill känna något äkta — berättelser som fastnar och ger dig något att tänka på i dagar.",
        cta_heading: "Vill du dela upplevelsen?",
        cta_body: "Hitta någon att se med — använd Se Sammen och matcha på en film som ger er något att prata om.",
        faq_question: "Vilka filmer är tunga och tankeväckande?",
        faq_answer: "Logflix kuraterar filmer och serier taggade «Tung och tankeväckande» — djupa, intensiva titlar som fastnar.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för något djupt?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Tung og tankevækkende – Film der sætter sig | Logflix",
        description: "Film og serier der sætter sig i dig længe efter rulleteksterne. Dybe, intense og uforglemmelige.",
        h1: "Tung og tankevækkende",
        intro: "Disse titler er ikke for dem der vil slappe af. De er for dem der vil mærke noget ægte — historier der sætter sig og giver dig noget at tænke over i dagevis.",
        cta_heading: "Vil du dele oplevelsen?",
        cta_body: "Find nogen at se med — brug Se Sammen og match på en film der giver jer noget at snakke om.",
        faq_question: "Hvilke film er tunge og tankevækkende?",
        faq_answer: "Logflix kuraterer film og serier tagget «Tung og tankevækkende» — dybe, intense titler der sætter sig.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til noget dybt?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Raskas ja ajatuksia herättävä – Elokuvat jotka jäävät mieleen | Logflix",
        description: "Elokuvia ja sarjoja jotka jäävät mieleen pitkäksi aikaa. Syviä, intensiivisiä ja unohtumattomia.",
        h1: "Raskas ja ajatuksia herättävä",
        intro: "Nämä nimikkeet eivät ole niille jotka haluavat rentoutua. Ne ovat niille jotka haluavat tuntea jotain aitoa — tarinoita jotka jäävät mieleen päiviksi.",
        cta_heading: "Haluatko jakaa kokemuksen?",
        cta_body: "Löydä joku katsomaan kanssasi — käytä Se Sammen ja löydä elokuva josta on puhuttavaa.",
        faq_question: "Mitkä elokuvat ovat raskaita ja ajatuksia herättäviä?",
        faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Tung og tankevekkende» — syviä, intensiivisiä nimikkeitä jotka jäävät mieleen.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis johonkin syvään?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "bra-for-hele-familien",
    mood_tags: ["Bra for hele familien"],
    locales: {
      no: {
        title: "Bra for hele familien – Familiefilmer og serier | Logflix",
        description: "Filmer og serier hele familien kan se sammen. Trygge, morsomme og engasjerende for alle aldre.",
        h1: "Bra for hele familien",
        intro: "Finn filmer og serier som passer for alle — fra de minste til de eldste. Trygge valg som hele familien kan nyte sammen.",
        cta_heading: "La hele familien velge sammen!",
        cta_body: "Bruk Se Sammen og la alle sveipe — finn filmen hele familien vil se.",
        faq_question: "Hvilke filmer passer for hele familien?",
        faq_answer: "Logflix kuraterer familievennlige filmer og serier tagget «Bra for hele familien» — trygge titler for alle aldre.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for familiekveld?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Bra för hela familjen – Familjefilmer och serier | Logflix",
        description: "Filmer och serier hela familjen kan se tillsammans. Trygga, roliga och engagerande för alla åldrar.",
        h1: "Bra för hela familjen",
        intro: "Hitta filmer och serier som passar alla — från de minsta till de äldsta. Trygga val som hela familjen kan njuta av tillsammans.",
        cta_heading: "Låt hela familjen välja tillsammans!",
        cta_body: "Använd Se Sammen och låt alla swipea — hitta filmen hela familjen vill se.",
        faq_question: "Vilka filmer passar för hela familjen?",
        faq_answer: "Logflix kuraterar familjevänliga filmer och serier taggade «Bra för hela familjen» — trygga titlar för alla åldrar.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för familjekväll?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "God for hele familien – Familiefilm og serier | Logflix",
        description: "Film og serier hele familien kan se sammen. Trygge, sjove og engagerende for alle aldre.",
        h1: "God for hele familien",
        intro: "Find film og serier der passer for alle — fra de mindste til de ældste. Trygge valg som hele familien kan nyde sammen.",
        cta_heading: "Lad hele familien vælge sammen!",
        cta_body: "Brug Se Sammen og lad alle swipe — find filmen hele familien vil se.",
        faq_question: "Hvilke film passer for hele familien?",
        faq_answer: "Logflix kuraterer familievenlige film og serier tagget «God for hele familien» — trygge titler for alle aldre.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til familieaften?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Sopii koko perheelle – Perhe-elokuvat ja sarjat | Logflix",
        description: "Elokuvia ja sarjoja jotka koko perhe voi katsoa yhdessä. Turvallisia, hauskoja ja mukaansatempaavia kaikenikäisille.",
        h1: "Sopii koko perheelle",
        intro: "Löydä elokuvia ja sarjoja jotka sopivat kaikille — pienimmistä vanhimpiin. Turvallisia valintoja joista koko perhe voi nauttia yhdessä.",
        cta_heading: "Anna koko perheen valita yhdessä!",
        cta_body: "Käytä Se Sammen ja anna kaikkien selata — löydä elokuva jota koko perhe haluaa katsoa.",
        faq_question: "Mitkä elokuvat sopivat koko perheelle?",
        faq_answer: "Logflix kuratoi perheystävällisiä elokuvia ja sarjoja tagilla «Bra for hele familien» — turvallisia nimikkeitä kaikenikäisille.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis perheiltaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "sen-kveld-alene",
    mood_tags: ["Sen kveld alene"],
    locales: {
      no: {
        title: "Sen kveld alene – Filmer for nattugla | Logflix",
        description: "Filmer og serier for de sene kveldene alene. Stemningsfulle, rolige og perfekt for natten.",
        h1: "Sen kveld alene",
        intro: "Klokka er sent, du er alene, og du trenger den rette filmen. Her er titler laget for nattens stille timer.",
        cta_heading: "Trenger du selskap?",
        cta_body: "Finn noen å se med — bruk Se Sammen og match på nattens film.",
        faq_question: "Hvilke filmer passer til sene kvelder alene?",
        faq_answer: "Logflix kuraterer filmer og serier tagget «Sen kveld alene» — stemningsfulle titler for nattugla.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for en sen kveld?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Sen kväll ensam – Filmer för nattugglan | Logflix",
        description: "Filmer och serier för de sena kvällarna ensam. Stämningsfulla, lugna och perfekta för natten.",
        h1: "Sen kväll ensam",
        intro: "Klockan är sen, du är ensam och behöver rätt film. Här är titlar gjorda för nattens tysta timmar.",
        cta_heading: "Behöver du sällskap?",
        cta_body: "Hitta någon att se med — använd Se Sammen och matcha på nattens film.",
        faq_question: "Vilka filmer passar till sena kvällar ensam?",
        faq_answer: "Logflix kuraterar filmer och serier taggade «Sen kväll ensam» — stämningsfulla titlar för nattugglan.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för en sen kväll?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Sen aften alene – Film for natuglen | Logflix",
        description: "Film og serier til de sene aftener alene. Stemningsfulde, rolige og perfekte til natten.",
        h1: "Sen aften alene",
        intro: "Klokken er sen, du er alene, og du har brug for den rigtige film. Her er titler lavet til nattens stille timer.",
        cta_heading: "Har du brug for selskab?",
        cta_body: "Find nogen at se med — brug Se Sammen og match på aftenens film.",
        faq_question: "Hvilke film passer til sene aftener alene?",
        faq_answer: "Logflix kuraterer film og serier tagget «Sen aften alene» — stemningsfulde titler for natuglen.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til en sen aften?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Myöhäinen ilta yksin – Elokuvat yökyöpelille | Logflix",
        description: "Elokuvia ja sarjoja myöhäisille illoille yksin. Tunnelmallisia, rauhallisia ja täydellisiä yöhön.",
        h1: "Myöhäinen ilta yksin",
        intro: "Kello on myöhä, olet yksin ja tarvitset oikean elokuvan. Tässä on nimikkeitä yön hiljaisille tunneille.",
        cta_heading: "Tarvitsetko seuraa?",
        cta_body: "Löydä joku katsomaan kanssasi — käytä Se Sammen ja löydä illan elokuva.",
        faq_question: "Mitkä elokuvat sopivat myöhäisille illoille yksin?",
        faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Sen kveld alene» — tunnelmallisia nimikkeitä yökyöpelille.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis myöhäiseen iltaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "imponér-gjestene",
    mood_tags: ["Imponér gjestene"],
    locales: {
      no: {
        title: "Imponér gjestene – Filmer som gjør inntrykk | Logflix",
        description: "Filmer og serier som imponerer gjestene dine. Perfekte valg for sosiale kvelder med venner.",
        h1: "Imponér gjestene",
        intro: "Har du gjester og vil vise at du har god smak? Her er titler som gjør inntrykk — filmer folk snakker om etterpå.",
        cta_heading: "La gjestene velge med!",
        cta_body: "Bruk Se Sammen og la alle sveipe — finn filmen hele gjengen vil se.",
        faq_question: "Hvilke filmer imponerer gjestene?",
        faq_answer: "Logflix kuraterer filmer og serier tagget «Imponér gjestene» — titler som gjør inntrykk i sosiale settinger.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for gjestene?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Imponera gästerna – Filmer som gör intryck | Logflix",
        description: "Filmer och serier som imponerar dina gäster. Perfekta val för sociala kvällar med vänner.",
        h1: "Imponera gästerna",
        intro: "Har du gäster och vill visa att du har bra smak? Här är titlar som gör intryck — filmer folk pratar om efteråt.",
        cta_heading: "Låt gästerna välja med!",
        cta_body: "Använd Se Sammen och låt alla swipea — hitta filmen hela gänget vill se.",
        faq_question: "Vilka filmer imponerar gästerna?",
        faq_answer: "Logflix kuraterar filmer och serier taggade «Imponera gästerna» — titlar som gör intryck i sociala sammanhang.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för gästerna?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Imponér gæsterne – Film der gør indtryk | Logflix",
        description: "Film og serier der imponerer dine gæster. Perfekte valg til sociale aftener med venner.",
        h1: "Imponér gæsterne",
        intro: "Har du gæster og vil vise at du har god smag? Her er titler der gør indtryk — film folk taler om bagefter.",
        cta_heading: "Lad gæsterne vælge med!",
        cta_body: "Brug Se Sammen og lad alle swipe — find filmen hele gruppen vil se.",
        faq_question: "Hvilke film imponerer gæsterne?",
        faq_answer: "Logflix kuraterer film og serier tagget «Imponér gæsterne» — titler der gør indtryk i sociale sammenhænge.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til gæsterne?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Tee vaikutus vieraisiin – Elokuvat jotka tekevät vaikutuksen | Logflix",
        description: "Elokuvia ja sarjoja jotka tekevät vaikutuksen vieraisiisi. Täydellisiä valintoja sosiaalisille illoille.",
        h1: "Tee vaikutus vieraisiin",
        intro: "Onko sinulla vieraita ja haluat näyttää hyvän makusi? Tässä on nimikkeitä jotka tekevät vaikutuksen — elokuvia joista puhutaan jälkeenpäin.",
        cta_heading: "Anna vieraiden valita mukana!",
        cta_body: "Käytä Se Sammen ja anna kaikkien selata — löydä elokuva jota koko porukka haluaa katsoa.",
        faq_question: "Mitkä elokuvat tekevät vaikutuksen vieraisiin?",
        faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Imponér gjestene» — nimikkeitä jotka tekevät vaikutuksen sosiaalisissa tilanteissa.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis vieraisiin?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "hyttekveld",
    mood_tags: ["Hyttekveld"],
    locales: {
      no: {
        title: "Hyttekveld – Filmer og serier for hytta | Logflix",
        description: "De beste filmene og seriene for en koselig hyttekveld. Perfekt med peisen på og kakao i koppen.",
        h1: "Hyttekveld",
        intro: "Peisen knitrer, kakaoen er varm, og du trenger den perfekte filmen. Her er titler laget for hyttekosen.",
        cta_heading: "Alle på hytta uenige?",
        cta_body: "La Se Sammen avgjøre — sveip hver for dere og finn filmen hele hytta vil se.",
        faq_question: "Hvilke filmer passer til hyttekveld?",
        faq_answer: "Logflix kuraterer filmer og serier tagget «Hyttekveld» — koselige titler perfekt for hytta.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for hyttekosen?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: {
        title: "Stugkväll – Filmer och serier för stugan | Logflix",
        description: "De bästa filmerna och serierna för en mysig stugkväll. Perfekt med brasan tänd och kakao i koppen.",
        h1: "Stugkväll",
        intro: "Brasan sprakar, kakao är varm och du behöver den perfekta filmen. Här är titlar gjorda för stugmyset.",
        cta_heading: "Alla på stugan oense?",
        cta_body: "Låt Se Sammen avgöra — swipea var för sig och hitta filmen hela stugan vill se.",
        faq_question: "Vilka filmer passar till stugkväll?",
        faq_answer: "Logflix kuraterar filmer och serier taggade «Stugkväll» — mysiga titlar perfekt för stugan.",
        empty: "Inga titlar hittades ännu. Kolla tillbaka snart!",
        breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides,
        faq_heading: "Vanliga frågor", bottom_heading: "Redo för stugmyset?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter.",
      },
      dk: {
        title: "Hyggeaften i sommerhuset – Film og serier | Logflix",
        description: "De bedste film og serier til en hyggelig aften i sommerhuset. Perfekt med pejsen tændt og kakao i koppen.",
        h1: "Hyggeaften i sommerhuset",
        intro: "Pejsen knitrer, kakaoen er varm, og du har brug for den perfekte film. Her er titler lavet til hyggen.",
        cta_heading: "Alle i sommerhuset uenige?",
        cta_body: "Lad Se Sammen afgøre — swipe hver for jer og find filmen hele huset vil se.",
        faq_question: "Hvilke film passer til hyggeaften?",
        faq_answer: "Logflix kuraterer film og serier tagget «Hyggeaften» — hyggelige titler perfekt til sommerhuset.",
        empty: "Ingen titler fundet endnu. Tjek tilbage snart!",
        breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides,
        faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til hyggen?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter.",
      },
      fi: {
        title: "Mökkiilta – Elokuvat ja sarjat mökille | Logflix",
        description: "Parhaat elokuvat ja sarjat tunnelmalliseen mökkiiltaan. Täydellistä takkatulen ja kaakaon kanssa.",
        h1: "Mökkiilta",
        intro: "Takka rätisee, kaakao on kuumaa ja tarvitset täydellisen elokuvan. Tässä on nimikkeitä mökkitunnelmaan.",
        cta_heading: "Kaikki mökillä eri mieltä?",
        cta_body: "Anna Se Sammen päättää — selaa erikseen ja löydä elokuva jota koko mökki haluaa katsoa.",
        faq_question: "Mitkä elokuvat sopivat mökkiiltaan?",
        faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Hyttekveld» — tunnelmallisia nimikkeitä mökille.",
        empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!",
        breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides,
        faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis mökkiiltaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen.",
      },
    },
  },
  {
    slug: "sommerkveld",
    mood_tags: ["Sommerkveld"],
    locales: {
      no: {
        title: "Sommerkveld – Filmer for lyse sommerkvelder | Logflix",
        description: "De beste filmene og seriene for lyse sommerkvelder. Lette, varme og fulle av sommerstemning.",
        h1: "Sommerkveld",
        intro: "Lange, lyse kvelder fortjener den rette filmen. Her er titler som fanger sommerstemningen — lette, varme og uforglemmelige.",
        cta_heading: "Sommerkveld med venner?", cta_body: "La Se Sammen finne filmen dere alle vil se.",
        faq_question: "Hvilke filmer passer til sommerkvelder?",
        faq_answer: "Logflix kuraterer filmer og serier tagget «Sommerkveld» — lette, varme titler med sommerstemning.",
        empty: "Ingen titler funnet ennå. Sjekk tilbake snart!",
        breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides,
        faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for sommer?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine.",
      },
      se: { title: "Sommarkväll – Filmer för ljusa sommarkvällar | Logflix", description: "De bästa filmerna och serierna för ljusa sommarkvällar.", h1: "Sommarkväll", intro: "Långa, ljusa kvällar förtjänar rätt film. Här är titlar som fångar sommarstämningen — lätta, varma och oförglömliga.", cta_heading: "Sommarkväll med vänner?", cta_body: "Låt Se Sammen hitta filmen ni alla vill se.", faq_question: "Vilka filmer passar till sommarkvällar?", faq_answer: "Logflix kuraterar filmer och serier taggade «Sommarkväll» — lätta, varma titlar med sommarstämning.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för sommaren?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Sommeraften – Film til lyse sommeraftener | Logflix", description: "De bedste film og serier til lyse sommeraftener.", h1: "Sommeraften", intro: "Lange, lyse aftener fortjener den rigtige film. Her er titler der fanger sommerstemningen — lette, varme og uforglemmelige.", cta_heading: "Sommeraften med venner?", cta_body: "Lad Se Sammen finde filmen I alle vil se.", faq_question: "Hvilke film passer til sommeraftener?", faq_answer: "Logflix kuraterer film og serier tagget «Sommeraften» — lette, varme titler med sommerstemning.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til sommer?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Kesäilta – Elokuvat valoisille kesäilloille | Logflix", description: "Parhaat elokuvat ja sarjat valoisille kesäilloille.", h1: "Kesäilta", intro: "Pitkät, valoisat illat ansaitsevat oikean elokuvan. Tässä on nimikkeitä jotka vangitsevat kesätunnelman — kevyitä, lämpimiä ja unohtumattomia.", cta_heading: "Kesäilta ystävien kanssa?", cta_body: "Anna Se Sammen löytää elokuva jota kaikki haluavat katsoa.", faq_question: "Mitkä elokuvat sopivat kesäiltoihin?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Sommerkveld» — kevyitä, lämpimiä nimikkeitä kesätunnelmaan.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis kesään?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "reisefilm",
    mood_tags: ["Reisefilm"],
    locales: {
      no: { title: "Reisefilmer – Filmer som gir reiselyst | Logflix", description: "Filmer og serier som gir deg reiselyst. Oppdag verden fra sofaen.", h1: "Reisefilmer", intro: "Kan du ikke reise akkurat nå? Disse filmene tar deg med til steder du drømmer om — fra sofaen.", cta_heading: "Planlegger dere reise?", cta_body: "La Se Sammen finne reisefilmen dere begge vil se.", faq_question: "Hvilke filmer gir reiselyst?", faq_answer: "Logflix kuraterer filmer og serier tagget «Reisefilm» — titler som tar deg med rundt i verden.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for en reise?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Resefilmer – Filmer som ger reslust | Logflix", description: "Filmer och serier som ger dig reslust. Upptäck världen från soffan.", h1: "Resefilmer", intro: "Kan du inte resa just nu? De här filmerna tar dig till platser du drömmer om — från soffan.", cta_heading: "Planerar ni resa?", cta_body: "Låt Se Sammen hitta resefilmen ni båda vill se.", faq_question: "Vilka filmer ger reslust?", faq_answer: "Logflix kuraterar filmer och serier taggade «Resefilmer» — titlar som tar dig runt i världen.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för en resa?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Rejsefilm – Film der giver rejselyst | Logflix", description: "Film og serier der giver dig rejselyst. Oplev verden fra sofaen.", h1: "Rejsefilm", intro: "Kan du ikke rejse lige nu? Disse film tager dig med til steder du drømmer om — fra sofaen.", cta_heading: "Planlægger I en rejse?", cta_body: "Lad Se Sammen finde rejsefilmen I begge vil se.", faq_question: "Hvilke film giver rejselyst?", faq_answer: "Logflix kuraterer film og serier tagget «Rejsefilm» — titler der tager dig med rundt i verden.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til en rejse?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Matkaelokuvat – Elokuvat jotka herättävät matkakuumeen | Logflix", description: "Elokuvia ja sarjoja jotka herättävät matkakuumeen. Löydä maailma sohvalta.", h1: "Matkaelokuvat", intro: "Etkö voi matkustaa juuri nyt? Nämä elokuvat vievät sinut paikkoihin joista unelmoit — sohvalta käsin.", cta_heading: "Suunnitteletteko matkaa?", cta_body: "Anna Se Sammen löytää matkaelokuva josta molemmat pitävät.", faq_question: "Mitkä elokuvat herättävät matkakuumeen?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Reisefilm» — nimikkeitä jotka vievät sinut ympäri maailmaa.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis matkalle?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "halloweenkveld",
    mood_tags: ["Halloweenkveld"],
    locales: {
      no: { title: "Halloweenkveld – Skumle filmer for Halloween | Logflix", description: "De beste filmene og seriene for Halloween. Skumle, uhyggelige og perfekt for kvelden.", h1: "Halloweenkveld", intro: "Gresskaret er utskåret og godteriet klart. Nå mangler bare den rette filmen — her er de skumleste titlene for Halloween.", cta_heading: "Halloween med venner?", cta_body: "La Se Sammen finne den skumleste filmen dere alle tør se.", faq_question: "Hvilke filmer passer til Halloween?", faq_answer: "Logflix kuraterer filmer og serier tagget «Halloweenkveld» — skumle titler perfekt for kvelden.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for Halloween?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Halloweenkväll – Läskiga filmer för Halloween | Logflix", description: "De bästa filmerna och serierna för Halloween. Läskiga, kusliga och perfekta för kvällen.", h1: "Halloweenkväll", intro: "Pumpan är urhålkad och godiset klart. Nu saknas bara rätt film — här är de läskigaste titlarna för Halloween.", cta_heading: "Halloween med vänner?", cta_body: "Låt Se Sammen hitta den läskigaste filmen ni alla vågar se.", faq_question: "Vilka filmer passar till Halloween?", faq_answer: "Logflix kuraterar filmer och serier taggade «Halloweenkväll» — läskiga titlar perfekt för kvällen.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för Halloween?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Halloweenaften – Uhyggelige film til Halloween | Logflix", description: "De bedste film og serier til Halloween. Uhyggelige, skræmmende og perfekte til aftenen.", h1: "Halloweenaften", intro: "Græskarret er udskåret og slikket klar. Nu mangler bare den rigtige film — her er de uhyggeligste titler til Halloween.", cta_heading: "Halloween med venner?", cta_body: "Lad Se Sammen finde den uhyggeligste film I alle tør se.", faq_question: "Hvilke film passer til Halloween?", faq_answer: "Logflix kuraterer film og serier tagget «Halloweenaften» — uhyggelige titler perfekt til aftenen.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til Halloween?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Halloween-ilta – Pelottavat elokuvat Halloweenille | Logflix", description: "Parhaat elokuvat ja sarjat Halloweenille. Pelottavia, karmaisevat ja täydellisiä iltaan.", h1: "Halloween-ilta", intro: "Kurpitsa on kaiverrettu ja karkit valmiina. Nyt puuttuu vain oikea elokuva — tässä ovat pelottavimmat nimikkeet Halloweenille.", cta_heading: "Halloween ystävien kanssa?", cta_body: "Anna Se Sammen löytää pelottavin elokuva jota kaikki uskaltavat katsoa.", faq_question: "Mitkä elokuvat sopivat Halloweenille?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Halloweenkveld» — pelottavia nimikkeitä illalle.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis Halloweeniin?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "grossere",
    mood_tags: ["Grøssere"],
    locales: {
      no: { title: "Grøssere – De beste skrekkfilmene | Logflix", description: "De beste grøsserne og skrekkfilmene. For deg som tør.", h1: "Grøssere", intro: "Liker du å bli skremt? Her er de beste grøsserne — fra psykologisk horror til jump scares som får deg til å hoppe.", cta_heading: "Hvem tør se med deg?", cta_body: "Bruk Se Sammen og finn den skumleste filmen dere begge tør se.", faq_question: "Hva er de beste grøsserne?", faq_answer: "Logflix kuraterer de beste grøsserne tagget med «Grøssere» — skrekkfilmer for de modige.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for skrekk?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Skräckfilm – De bästa rysarna | Logflix", description: "De bästa rysarna och skräckfilmerna. För dig som vågar.", h1: "Skräckfilm", intro: "Gillar du att bli skrämd? Här är de bästa rysarna — från psykologisk skräck till jump scares som får dig att hoppa.", cta_heading: "Vem vågar se med dig?", cta_body: "Använd Se Sammen och hitta den läskigaste filmen ni båda vågar se.", faq_question: "Vad är de bästa rysarna?", faq_answer: "Logflix kuraterar de bästa rysarna taggade med «Skräckfilm» — skräckfilmer för de modiga.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för skräck?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Gyserfilm – De bedste gysere | Logflix", description: "De bedste gysere og horrorfilm. For dig der tør.", h1: "Gyserfilm", intro: "Kan du lide at blive skræmt? Her er de bedste gysere — fra psykologisk horror til jump scares der får dig til at hoppe.", cta_heading: "Hvem tør se med dig?", cta_body: "Brug Se Sammen og find den uhyggeligste film I begge tør se.", faq_question: "Hvad er de bedste gysere?", faq_answer: "Logflix kuraterer de bedste gysere tagget med «Gyserfilm» — horrorfilm for de modige.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til gys?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Kauhuelokuvat – Parhaat kauhuelokuvat | Logflix", description: "Parhaat kauhuelokuvat ja jännärit. Niille jotka uskaltavat.", h1: "Kauhuelokuvat", intro: "Pidätkö pelästymisestä? Tässä ovat parhaat kauhuelokuvat — psykologisesta kauhusta hyppypelotuksiin.", cta_heading: "Kuka uskaltaa katsoa kanssasi?", cta_body: "Käytä Se Sammen ja löydä pelottavin elokuva jota molemmat uskaltavat katsoa.", faq_question: "Mitkä ovat parhaat kauhuelokuvat?", faq_answer: "Logflix kuratoi parhaita kauhuelokuvia tagilla «Grøssere» — kauhuelokuvia rohkeille.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis kauhuun?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "familiekos",
    mood_tags: ["Familiekos"],
    locales: {
      no: { title: "Familiekos – Filmer for hele familien | Logflix", description: "Varme, koselige filmer og serier for familiekos. Perfekt for helgen.", h1: "Familiekos", intro: "Noen ganger er alt du trenger en varm film og hele familien samlet. Her er titlene som gir ekte familiekos.", cta_heading: "La familien velge sammen!", cta_body: "Bruk Se Sammen og la alle sveipe — finn filmen hele familien elsker.", faq_question: "Hvilke filmer gir familiekos?", faq_answer: "Logflix kuraterer filmer og serier tagget «Familiekos» — varme, trygge titler for hele familien.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for familiekos?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Familjemys – Filmer för hela familjen | Logflix", description: "Varma, mysiga filmer och serier för familjemys. Perfekt för helgen.", h1: "Familjemys", intro: "Ibland är allt du behöver en varm film och hela familjen samlad. Här är titlarna som ger äkta familjemys.", cta_heading: "Låt familjen välja tillsammans!", cta_body: "Använd Se Sammen och låt alla swipea — hitta filmen hela familjen älskar.", faq_question: "Vilka filmer ger familjemys?", faq_answer: "Logflix kuraterar filmer och serier taggade «Familjemys» — varma, trygga titlar för hela familjen.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för familjemys?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Familiehygge – Film for hele familien | Logflix", description: "Varme, hyggelige film og serier til familiehygge. Perfekt til weekenden.", h1: "Familiehygge", intro: "Nogle gange er alt du har brug for en varm film og hele familien samlet. Her er titlene der giver ægte familiehygge.", cta_heading: "Lad familien vælge sammen!", cta_body: "Brug Se Sammen og lad alle swipe — find filmen hele familien elsker.", faq_question: "Hvilke film giver familiehygge?", faq_answer: "Logflix kuraterer film og serier tagget «Familiehygge» — varme, trygge titler for hele familien.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til familiehygge?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Perheen yhteinen ilta – Elokuvat koko perheelle | Logflix", description: "Lämpimiä, tunnelmallisia elokuvia ja sarjoja perheillalle. Täydellistä viikonlopulle.", h1: "Perheen yhteinen ilta", intro: "Joskus tarvitset vain lämpimän elokuvan ja koko perheen koolla. Tässä ovat nimikkeet jotka luovat aitoa perhetunnelmaa.", cta_heading: "Anna perheen valita yhdessä!", cta_body: "Käytä Se Sammen ja anna kaikkien selata — löydä elokuva jota koko perhe rakastaa.", faq_question: "Mitkä elokuvat sopivat perheillalle?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Familiekos» — lämpimiä, turvallisia nimikkeitä koko perheelle.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis perheiltaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "barnefilm",
    mood_tags: ["Barnefilm"],
    locales: {
      no: { title: "Barnefilmer – De beste filmene for barn | Logflix", description: "De beste barnefilmene og seriene. Trygge, morsomme og engasjerende for de minste.", h1: "Barnefilmer", intro: "Finn de beste filmene og seriene for barn — trygge valg som de minste elsker og de voksne tåler.", cta_heading: "La barna velge!", cta_body: "Bruk Se Sammen og la hele familien sveipe — finn filmen alle vil se.", faq_question: "Hvilke filmer passer for barn?", faq_answer: "Logflix kuraterer barnefilmer tagget «Barnefilm» — trygge, engasjerende titler for de minste.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for barnefilm?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Barnfilmer – De bästa filmerna för barn | Logflix", description: "De bästa barnfilmerna och serierna. Trygga, roliga och engagerande för de minsta.", h1: "Barnfilmer", intro: "Hitta de bästa filmerna och serierna för barn — trygga val som de minsta älskar och de vuxna tål.", cta_heading: "Låt barnen välja!", cta_body: "Använd Se Sammen och låt hela familjen swipea — hitta filmen alla vill se.", faq_question: "Vilka filmer passar för barn?", faq_answer: "Logflix kuraterar barnfilmer taggade «Barnfilmer» — trygga, engagerande titlar för de minsta.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för barnfilm?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Børnefilm – De bedste film for børn | Logflix", description: "De bedste børnefilm og serier. Trygge, sjove og engagerende for de mindste.", h1: "Børnefilm", intro: "Find de bedste film og serier for børn — trygge valg som de mindste elsker og de voksne tåler.", cta_heading: "Lad børnene vælge!", cta_body: "Brug Se Sammen og lad hele familien swipe — find filmen alle vil se.", faq_question: "Hvilke film passer for børn?", faq_answer: "Logflix kuraterer børnefilm tagget «Børnefilm» — trygge, engagerende titler for de mindste.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til børnefilm?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Lastenelokuvat – Parhaat elokuvat lapsille | Logflix", description: "Parhaat lastenelokuvat ja sarjat. Turvallisia, hauskoja ja mukaansatempaavia pienimmille.", h1: "Lastenelokuvat", intro: "Löydä parhaat elokuvat ja sarjat lapsille — turvallisia valintoja joita pienimmät rakastavat ja aikuiset sietävät.", cta_heading: "Anna lasten valita!", cta_body: "Käytä Se Sammen ja anna koko perheen selata — löydä elokuva jota kaikki haluavat katsoa.", faq_question: "Mitkä elokuvat sopivat lapsille?", faq_answer: "Logflix kuratoi lastenelokuvia tagilla «Barnefilm» — turvallisia, mukaansatempaavia nimikkeitä pienimmille.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis lastenelokuviin?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "basert-pa-en-sann-historie",
    mood_tags: ["Basert på en sann historie"],
    locales: {
      no: { title: "Basert på en sann historie – Filmer og serier | Logflix", description: "De beste filmene og seriene basert på sanne historier. Gripende, inspirerende og ekte.", h1: "Basert på en sann historie", intro: "De sterkeste historiene trenger ingen fiksjon. Her er filmer og serier basert på virkelige hendelser — gripende og uforglemmelige.", cta_heading: "Finn en å se med!", cta_body: "Bruk Se Sammen og match på en film basert på virkeligheten.", faq_question: "Hvilke filmer er basert på sanne historier?", faq_answer: "Logflix kuraterer filmer og serier tagget «Basert på en sann historie» — gripende titler fra virkeligheten.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for virkeligheten?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Baserad på en sann historia – Filmer och serier | Logflix", description: "De bästa filmerna och serierna baserade på sanna historier. Gripande, inspirerande och äkta.", h1: "Baserad på en sann historia", intro: "De starkaste berättelserna behöver ingen fiktion. Här är filmer och serier baserade på verkliga händelser — gripande och oförglömliga.", cta_heading: "Hitta någon att se med!", cta_body: "Använd Se Sammen och matcha på en film baserad på verkligheten.", faq_question: "Vilka filmer är baserade på sanna historier?", faq_answer: "Logflix kuraterar filmer och serier taggade «Baserad på en sann historia» — gripande titlar från verkligheten.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för verkligheten?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Baseret på en sand historie – Film og serier | Logflix", description: "De bedste film og serier baseret på sande historier. Gribende, inspirerende og ægte.", h1: "Baseret på en sand historie", intro: "De stærkeste historier behøver ingen fiktion. Her er film og serier baseret på virkelige begivenheder — gribende og uforglemmelige.", cta_heading: "Find nogen at se med!", cta_body: "Brug Se Sammen og match på en film baseret på virkeligheden.", faq_question: "Hvilke film er baseret på sande historier?", faq_answer: "Logflix kuraterer film og serier tagget «Baseret på en sand historie» — gribende titler fra virkeligheden.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til virkeligheden?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Tositapahtumiin perustuva – Elokuvat ja sarjat | Logflix", description: "Parhaat tositapahtumiin perustuvat elokuvat ja sarjat. Koskettavia, inspiroivia ja aitoja.", h1: "Tositapahtumiin perustuva", intro: "Voimakkaimmat tarinat eivät tarvitse fiktiota. Tässä on elokuvia ja sarjoja todellisiin tapahtumiin perustuen — koskettavia ja unohtumattomia.", cta_heading: "Löydä joku katsomaan kanssasi!", cta_body: "Käytä Se Sammen ja löydä todellisuuteen perustuva elokuva.", faq_question: "Mitkä elokuvat perustuvat tositapahtumiin?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Basert på en sann historie» — koskettavia nimikkeitä todellisuudesta.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis todellisuuteen?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "kort-og-konsist",
    mood_tags: ["Kort og konsist"],
    locales: {
      no: { title: "Kort og konsist – Filmer under 100 minutter | Logflix", description: "Korte, konsise filmer og serier som ikke kaster bort tiden din. Rett på sak.", h1: "Kort og konsist", intro: "Ikke tid til en tretimersepos? Her er filmer og serier som går rett på sak — korte, men kraftfulle.", cta_heading: "Kort på tid?", cta_body: "Bruk Se Sammen og finn en kort film dere begge vil se — på under ett minutt.", faq_question: "Hvilke filmer er korte og konsise?", faq_answer: "Logflix kuraterer filmer og serier tagget «Kort og konsist» — titler som respekterer tiden din.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for noe kort?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Kort och koncist – Filmer under 100 minuter | Logflix", description: "Korta, koncisa filmer och serier som inte slösar din tid. Rakt på sak.", h1: "Kort och koncist", intro: "Inte tid för ett tretimmars epos? Här är filmer och serier som går rakt på sak — korta men kraftfulla.", cta_heading: "Kort om tid?", cta_body: "Använd Se Sammen och hitta en kort film ni båda vill se — på under en minut.", faq_question: "Vilka filmer är korta och koncisa?", faq_answer: "Logflix kuraterar filmer och serier taggade «Kort och koncist» — titlar som respekterar din tid.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för något kort?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Kort og præcis – Film under 100 minutter | Logflix", description: "Korte, præcise film og serier der ikke spilder din tid. Direkte til sagen.", h1: "Kort og præcis", intro: "Ikke tid til et tretimers epos? Her er film og serier der går direkte til sagen — korte men kraftfulde.", cta_heading: "Kort på tid?", cta_body: "Brug Se Sammen og find en kort film I begge vil se — på under ét minut.", faq_question: "Hvilke film er korte og præcise?", faq_answer: "Logflix kuraterer film og serier tagget «Kort og præcis» — titler der respekterer din tid.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til noget kort?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Lyhyt ja ytimekäs – Alle 100 minuutin elokuvat | Logflix", description: "Lyhyitä, ytimekkäitä elokuvia ja sarjoja jotka eivät tuhlaa aikaasi. Suoraan asiaan.", h1: "Lyhyt ja ytimekäs", intro: "Ei aikaa kolmen tunnin eepokselle? Tässä on elokuvia ja sarjoja jotka menevät suoraan asiaan — lyhyitä mutta voimakkaita.", cta_heading: "Vähän aikaa?", cta_body: "Käytä Se Sammen ja löydä lyhyt elokuva josta molemmat pitävät — alle minuutissa.", faq_question: "Mitkä elokuvat ovat lyhyitä ja ytimekkäitä?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Kort og konsist» — nimikkeitä jotka kunnioittavat aikaasi.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis johonkin lyhyeen?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "visuelt-mesterverk",
    mood_tags: ["Visuelt mesterverk"],
    locales: {
      no: { title: "Visuelt mesterverk – Filmer med fantastisk foto | Logflix", description: "Visuelt slående filmer og serier. Fantastisk foto, vakre bilder og cinematisk kunst.", h1: "Visuelt mesterverk", intro: "Noen filmer er kunst du kan se på. Her er titlene med det mest fantastiske fotoarbeidet — visuell poesi på skjermen.", cta_heading: "Del den visuelle opplevelsen!", cta_body: "Bruk Se Sammen og finn et visuelt mesterverk dere begge vil se.", faq_question: "Hvilke filmer er visuelle mesterverk?", faq_answer: "Logflix kuraterer filmer og serier tagget «Visuelt mesterverk» — titler med enestående foto og visuell kunst.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for noe vakkert?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Visuellt mästerverk – Filmer med fantastiskt foto | Logflix", description: "Visuellt slående filmer och serier. Fantastiskt foto, vackra bilder och cinematisk konst.", h1: "Visuellt mästerverk", intro: "Vissa filmer är konst du kan titta på. Här är titlarna med det mest fantastiska fotoarbetet — visuell poesi på skärmen.", cta_heading: "Dela den visuella upplevelsen!", cta_body: "Använd Se Sammen och hitta ett visuellt mästerverk ni båda vill se.", faq_question: "Vilka filmer är visuella mästerverk?", faq_answer: "Logflix kuraterar filmer och serier taggade «Visuellt mästerverk» — titlar med enastående foto och visuell konst.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för något vackert?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Visuelt mesterværk – Film med fantastisk foto | Logflix", description: "Visuelt slående film og serier. Fantastisk foto, smukke billeder og cinematisk kunst.", h1: "Visuelt mesterværk", intro: "Nogle film er kunst du kan se på. Her er titlene med det mest fantastiske fotoarbejde — visuel poesi på skærmen.", cta_heading: "Del den visuelle oplevelse!", cta_body: "Brug Se Sammen og find et visuelt mesterværk I begge vil se.", faq_question: "Hvilke film er visuelle mesterværker?", faq_answer: "Logflix kuraterer film og serier tagget «Visuelt mesterværk» — titler med enestående foto og visuel kunst.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til noget smukt?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Visuaalinen mestariteos – Elokuvat upealla kuvauksella | Logflix", description: "Visuaalisesti häikäiseviä elokuvia ja sarjoja. Upeaa kuvausta, kauniita kuvia ja elokuvataidetta.", h1: "Visuaalinen mestariteos", intro: "Jotkut elokuvat ovat taidetta jota voi katsoa. Tässä ovat nimikkeet joissa on upein kuvaustyö — visuaalista runoutta näytöllä.", cta_heading: "Jaa visuaalinen kokemus!", cta_body: "Käytä Se Sammen ja löydä visuaalinen mestariteos jota molemmat haluavat katsoa.", faq_question: "Mitkä elokuvat ovat visuaalisia mestariteoksia?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Visuelt mesterverk» — nimikkeitä joissa on poikkeuksellista kuvausta ja visuaalista taidetta.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis johonkin kauniiseen?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "nostalgisk-perle",
    mood_tags: ["Nostalgisk perle"],
    locales: {
      no: { title: "Nostalgiske perler – Klassikere og gjenglemte favoritter | Logflix", description: "Nostalgiske filmer og serier som tar deg tilbake. Klassikere og gjenglemte favoritter.", h1: "Nostalgiske perler", intro: "Noen filmer tar deg rett tilbake til en annen tid. Her er nostalgiske perler — klassikere og gjenglemte favoritter som fortjener å bli sett igjen.", cta_heading: "Del nostalgien!", cta_body: "Bruk Se Sammen og finn en nostalgisk perle dere begge vil gjenoppleve.", faq_question: "Hvilke filmer er nostalgiske perler?", faq_answer: "Logflix kuraterer filmer og serier tagget «Nostalgisk perle» — klassikere og gjenglemte favoritter.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for nostalgi?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Nostalgiska pärlor – Klassiker och bortglömda favoriter | Logflix", description: "Nostalgiska filmer och serier som tar dig tillbaka. Klassiker och bortglömda favoriter.", h1: "Nostalgiska pärlor", intro: "Vissa filmer tar dig rakt tillbaka till en annan tid. Här är nostalgiska pärlor — klassiker och bortglömda favoriter som förtjänar att ses igen.", cta_heading: "Dela nostalgin!", cta_body: "Använd Se Sammen och hitta en nostalgisk pärla ni båda vill återuppleva.", faq_question: "Vilka filmer är nostalgiska pärlor?", faq_answer: "Logflix kuraterar filmer och serier taggade «Nostalgiska pärlor» — klassiker och bortglömda favoriter.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för nostalgi?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Nostalgiske perler – Klassikere og glemte favoritter | Logflix", description: "Nostalgiske film og serier der tager dig tilbage. Klassikere og glemte favoritter.", h1: "Nostalgiske perler", intro: "Nogle film tager dig direkte tilbage til en anden tid. Her er nostalgiske perler — klassikere og glemte favoritter der fortjener at blive set igen.", cta_heading: "Del nostalgien!", cta_body: "Brug Se Sammen og find en nostalgisk perle I begge vil genopleve.", faq_question: "Hvilke film er nostalgiske perler?", faq_answer: "Logflix kuraterer film og serier tagget «Nostalgiske perler» — klassikere og glemte favoritter.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til nostalgi?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Nostalgisia helmiä – Klassikoita ja unohdettuja suosikkeja | Logflix", description: "Nostalgisia elokuvia ja sarjoja jotka vievät sinut takaisin. Klassikoita ja unohdettuja suosikkeja.", h1: "Nostalgisia helmiä", intro: "Jotkut elokuvat vievät sinut suoraan toiseen aikaan. Tässä on nostalgisia helmiä — klassikoita ja unohdettuja suosikkeja jotka ansaitsevat tulla nähdyksi uudelleen.", cta_heading: "Jaa nostalgia!", cta_body: "Käytä Se Sammen ja löydä nostalginen helmi jota molemmat haluavat kokea uudelleen.", faq_question: "Mitkä elokuvat ovat nostalgisia helmiä?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Nostalgisk perle» — klassikoita ja unohdettuja suosikkeja.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis nostalgiaan?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "skjult-skatt",
    mood_tags: ["Skjult skatt"],
    locales: {
      no: { title: "Skjulte skatter – Filmer du ikke visste du trengte | Logflix", description: "Undervurderte filmer og serier du sannsynligvis har gått glipp av. Skjulte skatter verdt å oppdage.", h1: "Skjulte skatter", intro: "Noen av de beste filmene er de ingen snakker om. Her er skjulte skatter — undervurderte titler du sannsynligvis har gått glipp av.", cta_heading: "Oppdage sammen?", cta_body: "Bruk Se Sammen og finn en skjult skatt dere begge vil oppdage.", faq_question: "Hva er skjulte skatter?", faq_answer: "Logflix kuraterer filmer og serier tagget «Skjult skatt» — undervurderte titler som fortjener mer oppmerksomhet.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for å oppdage?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Dolda skatter – Filmer du inte visste att du behövde | Logflix", description: "Underskattade filmer och serier du troligen har missat. Dolda skatter värda att upptäcka.", h1: "Dolda skatter", intro: "Några av de bästa filmerna är de som ingen pratar om. Här är dolda skatter — underskattade titlar du troligen har missat.", cta_heading: "Upptäck tillsammans?", cta_body: "Använd Se Sammen och hitta en dold skatt ni båda vill upptäcka.", faq_question: "Vad är dolda skatter?", faq_answer: "Logflix kuraterar filmer och serier taggade «Dolda skatter» — underskattade titlar som förtjänar mer uppmärksamhet.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo att upptäcka?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Skjulte skatte – Film du ikke vidste du havde brug for | Logflix", description: "Undervurderede film og serier du sandsynligvis har overset. Skjulte skatte værd at opdage.", h1: "Skjulte skatte", intro: "Nogle af de bedste film er dem ingen taler om. Her er skjulte skatte — undervurderede titler du sandsynligvis har overset.", cta_heading: "Opdag sammen?", cta_body: "Brug Se Sammen og find en skjult skat I begge vil opdage.", faq_question: "Hvad er skjulte skatte?", faq_answer: "Logflix kuraterer film og serier tagget «Skjulte skatte» — undervurderede titler der fortjener mere opmærksomhed.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til at opdage?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Piilotettuja aarteita – Elokuvat joita et tiennyt tarvitsevasi | Logflix", description: "Aliarvostettuja elokuvia ja sarjoja joita olet todennäköisesti ohittanut. Piilotettuja aarteita löydettäväksi.", h1: "Piilotettuja aarteita", intro: "Jotkut parhaista elokuvista ovat niitä joista kukaan ei puhu. Tässä on piilotettuja aarteita — aliarvostettuja nimikkeitä joita olet todennäköisesti ohittanut.", cta_heading: "Löytäkää yhdessä?", cta_body: "Käytä Se Sammen ja löydä piilotettu aarre jota molemmat haluavat löytää.", faq_question: "Mitä ovat piilotetut aarteet?", faq_answer: "Logflix kuratoi elokuvia ja sarjoja tagilla «Skjult skatt» — aliarvostettuja nimikkeitä jotka ansaitsevat enemmän huomiota.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis löytämään?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
  {
    slug: "paskekrim",
    mood_tags: ["Påskekrim"],
    locales: {
      no: { title: "Påskekrim – De beste krimseriene for påsken | Logflix", description: "De beste påskekrim-seriene. Finn hvor du kan strømme dem i Norden.", h1: "Påskekrim", intro: "Påsken er ikke komplett uten en god krimserie. Her er de beste påskekrim-titlene — kuratert med mood tags.", cta_heading: "Kan ikke bestemme dere for påskekrimen?", cta_body: "La Se Sammen avgjøre — sveip hver for dere og finn krimserien dere begge vil se.", faq_question: "Hvilke serier passer til påskekrim?", faq_answer: "Logflix kuraterer påskekrim-serier tagget «Påskekrim» — perfekte titler for påskehelgen.", empty: "Ingen titler funnet ennå. Sjekk tilbake snart!", breadcrumb_home: bc("no").home, breadcrumb_guides: bc("no").guides, faq_heading: "Ofte stilte spørsmål", bottom_heading: "Klar for påskekrimen?", bottom_body: "Opprett en gratis konto og begynn å logge favorittene dine." },
      se: { title: "Påskdeckare – De bästa krimserierna för påsken | Logflix", description: "De bästa påskdeckarna. Hitta var du kan streama dem i Norden.", h1: "Påskdeckare", intro: "Påsken är inte komplett utan en bra krimserie. Här är de bästa påskdeckarna — kuraterade med mood tags.", cta_heading: "Kan ni inte bestämma er för påskdeckaren?", cta_body: "Låt Se Sammen avgöra — swipea var för sig och hitta krimserien ni båda vill se.", faq_question: "Vilka serier passar till påskdeckare?", faq_answer: "Logflix kuraterar påskdeckare taggade «Påskekrim» — perfekta titlar för påskhelgen.", empty: "Inga titlar hittades ännu. Kolla tillbaka snart!", breadcrumb_home: bc("se").home, breadcrumb_guides: bc("se").guides, faq_heading: "Vanliga frågor", bottom_heading: "Redo för påskdeckaren?", bottom_body: "Skapa ett gratis konto och börja logga dina favoriter." },
      dk: { title: "Påskekrimi – De bedste krimiserier til påsken | Logflix", description: "De bedste påskekrimi-serier. Find hvor du kan streame dem i Norden.", h1: "Påskekrimi", intro: "Påsken er ikke komplet uden en god krimiserie. Her er de bedste påskekrimi-titler — kurateret med mood tags.", cta_heading: "Kan I ikke bestemme jer for påskekrimien?", cta_body: "Lad Se Sammen afgøre — swipe hver for jer og find krimiserien I begge vil se.", faq_question: "Hvilke serier passer til påskekrimi?", faq_answer: "Logflix kuraterer påskekrimi-serier tagget «Påskekrimi» — perfekte titler til påskehelgen.", empty: "Ingen titler fundet endnu. Tjek tilbage snart!", breadcrumb_home: bc("dk").home, breadcrumb_guides: bc("dk").guides, faq_heading: "Ofte stillede spørgsmål", bottom_heading: "Klar til påskekrimien?", bottom_body: "Opret en gratis konto og begynd at logge dine favoritter." },
      fi: { title: "Pääsiäisdekkarit – Parhaat jännityssarjat pääsiäiseksi | Logflix", description: "Parhaat pääsiäisdekkarit. Löydä missä voit striimata ne Pohjoismaissa.", h1: "Pääsiäisdekkarit", intro: "Pääsiäinen ei ole täydellinen ilman hyvää jännityssarjaa. Tässä ovat parhaat pääsiäisdekkarit — kuratoitu mood-tageilla.", cta_heading: "Etkö pääse sopimukseen pääsiäisdekkarista?", cta_body: "Anna Se Sammen päättää — selaa erikseen ja löydä jännityssarja josta molemmat pitävät.", faq_question: "Mitkä sarjat sopivat pääsiäisdekkariksi?", faq_answer: "Logflix kuratoi pääsiäisdekkarisarjoja tagilla «Påskekrim» — täydellisiä nimikkeitä pääsiäisviikonlopulle.", empty: "Nimikkeitä ei löytynyt vielä. Tarkista myöhemmin!", breadcrumb_home: bc("fi").home, breadcrumb_guides: bc("fi").guides, faq_heading: "Usein kysytyt kysymykset", bottom_heading: "Valmis pääsiäisdekkariin?", bottom_body: "Luo ilmainen tili ja aloita suosikkiesi kirjaaminen." },
    },
  },
];
